/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmacyRole;

import Business.EcoSystem;
import Business.Enterprise.PharmacyEnterprise;
import Business.Stock.Stock;
import Business.WorkQueue.DoctorPrescriptionToPharmacy;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AustinGnanaraj
 */
public class ManageRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRequestsJPanel
     */
    JPanel userProcessContainer;
    EcoSystem eco;
    PharmacyEnterprise enterprise;
    Stock s;
    DoctorPrescriptionToPharmacy de;

    public ManageRequestsJPanel(JPanel userProcessContainer, EcoSystem eco, PharmacyEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.eco = eco;
        this.enterprise = enterprise;
        populateTable();
        btnProcessRequest.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        btnCheckAvailability = new javax.swing.JButton();
        btnProcessRequest = new javax.swing.JButton();
        btnRequestStocks = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Drug Name", "Requested By", "Quantity", "EnterpriseName"
            }
        ));
        jScrollPane1.setViewportView(tblRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 920, 100));

        btnCheckAvailability.setText("Check Availability of Drug");
        btnCheckAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAvailabilityActionPerformed(evt);
            }
        });
        add(btnCheckAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 250, 50));

        btnProcessRequest.setText("Process Request");
        btnProcessRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessRequestActionPerformed(evt);
            }
        });
        add(btnProcessRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 290, 50));

        btnRequestStocks.setText("Request Stocks");
        btnRequestStocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestStocksActionPerformed(evt);
            }
        });
        add(btnRequestStocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 280, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessRequestActionPerformed
        de.setStatus("Completed");
        s.setQuantity(s.getQuantity() - de.getQuantityOfDrugs());
        populateTable();


    }//GEN-LAST:event_btnProcessRequestActionPerformed

    private void btnCheckAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAvailabilityActionPerformed
        int selectedRow = tblRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        de = (DoctorPrescriptionToPharmacy) tblRequests.getValueAt(selectedRow, 0);
        boolean a = true;
        int b = enterprise.getStockDirectory().getStockDirectory().size();
        if (b > 0) {
            for (Stock s : enterprise.getStockDirectory().getStockDirectory()) {
                if (de.getDrug().getDrugName().equals(s.getDrug().getDrugName()) && de.getQuantityOfDrugs() <= s.getQuantity()) {
                    JOptionPane.showMessageDialog(null, "Stock is Available");
                    this.s = s;
                    btnProcessRequest.setEnabled(true);
                    break;
                }
            }
        } else {
            a = false;
        }
        if (a == false) {
            JOptionPane.showMessageDialog(null, "Stock is not available");
            return;
        }


    }//GEN-LAST:event_btnCheckAvailabilityActionPerformed

    private void btnRequestStocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestStocksActionPerformed
        OrderDrugsFromManufacturerJPanel odm = new OrderDrugsFromManufacturerJPanel(userProcessContainer, eco,enterprise);
        userProcessContainer.add("manageOrganizationJPanel", odm);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRequestStocksActionPerformed

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblRequests.getModel();
        model.setRowCount(0);
        for (WorkRequest e : eco.getDrugPrescriptionDirectory().getWorkRequestList()) {
            DoctorPrescriptionToPharmacy eb = (DoctorPrescriptionToPharmacy) e;
            if (eb.getQuantityOfDrugs() > 0 && eb.getStatus() == "requested") {
                Object row[] = new Object[4];
                row[0] = eb;
                row[1] = eb.getDoctor().getName();
                row[2] = eb.getQuantityOfDrugs();
                row[3] = eb.getHospitalEnterprise().getName();
                model.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckAvailability;
    private javax.swing.JButton btnProcessRequest;
    private javax.swing.JButton btnRequestStocks;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequests;
    // End of variables declaration//GEN-END:variables
}
