/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmacyRole;

import Business.Drug.Drug;
import Business.EcoSystem;
import Business.Enterprise.DrugEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.Network;
import Business.WorkQueue.PharmacyRequestToManufacturerer;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AustinGnanaraj
 */
public class OrderDrugsFromManufacturerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderDrugsFromManufacturerJPanel
     */
    JPanel userProcessContainer;
    EcoSystem eco;
    PharmacyEnterprise enterprise;
    //Drug d;

    public OrderDrugsFromManufacturerJPanel(JPanel userProcessContainer, EcoSystem eco, PharmacyEnterprise enterprise) {
        initComponents();
        this.eco = eco;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateManufacturerer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 290, 60));

        jLabel1.setText("Quantity");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 160, 60));

        jLabel2.setText("Drug Manufacturer");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 160, 60));

        jLabel3.setText("Drug Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 160, 60));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 290, 60));
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 290, 60));

        jButton1.setText("Submit Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 290, 50));

        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 210, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        DrugEnterprise network = (DrugEnterprise) jComboBox1.getSelectedItem();
        if (network != null) {
            populateDrugs(network);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PharmacyRequestToManufacturerer pr = new PharmacyRequestToManufacturerer();

        DrugEnterprise de = (DrugEnterprise) jComboBox1.getSelectedItem();
        pr.setPharmacyEnterprise(enterprise);
        pr.setDrugEnterprise(de);
        Drug d = (Drug) jComboBox2.getSelectedItem();
        int q = (int) jSpinner1.getValue();
        pr.setDrug(d);
        pr.setQuantityOfDrugs(q);
        pr.setStatus("pending");
        eco.getDrugRequestToManufacturer().getWorkRequestList().add(pr);
        JOptionPane.showMessageDialog(null, "Submitted");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void populateManufacturerer() {
        jComboBox1.removeAllItems();
        for (Network n : eco.getNetworkList()) {
            for (Enterprise de : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (de instanceof DrugEnterprise) {
                    jComboBox1.addItem(de);

                }
            }
        }
    }

    private void populateDrugs(DrugEnterprise de) {
        jComboBox2.removeAllItems();
        for (Drug d : de.getDrugDirectory().getDrugDirectory()) {
            jComboBox2.addItem(d);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
