/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.EcoSystem;
import Business.Encounter.Encounter;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AustinGnanaraj
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    Patient patient;
    private UserAccount account;
    EcoSystem eco;

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    public PatientWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, EcoSystem eco) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.eco = eco;
        this.account = account;
        populateTable();

    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) detailsJTable.getModel();
        dtm.setRowCount(0);

        for (Patient patient : ((HospitalEnterprise) enterprise).getPatientDirectory().getPatientDirectory()) {

            for (Encounter e : patient.getEncounterHistory().getEncounterHistory()) {
                if (account.getPerson().getSsn().equals(patient.getSsn())) {

                    Object[] row = new Object[8];
                    row[0] = e;
                    row[1] = e.getDoctorName();
                    row[2] = e.getDescriptionOfComplaint();
                    row[3] = e.getDiagnosis();

                    dtm.addRow(row);

                }

            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientworkLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsJTable = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDrugReviews = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientworkLabel.setText("Patient WorkArea");
        add(patientworkLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        detailsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Time", "Doctor Name", "Description of Complaint", "Prescription"
            }
        ));
        jScrollPane1.setViewportView(detailsJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 1000, 110));

        refreshJButton.setText("Refresh>>");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Message", "Sender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 410, 100));

        btnDrugReviews.setText("Drug Reviews");
        btnDrugReviews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrugReviewsActionPerformed(evt);
            }
        });
        add(btnDrugReviews, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 270, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:

        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void btnDrugReviewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrugReviewsActionPerformed
        PatientDrugReviewJPanel ap = new PatientDrugReviewJPanel(userProcessContainer, enterprise,eco,account);
        userProcessContainer.add("Add Patient", ap);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDrugReviewsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDrugReviews;
    private javax.swing.JTable detailsJTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel patientworkLabel;
    private javax.swing.JButton refreshJButton;
    // End of variables declaration//GEN-END:variables
}
