/*
 * AdminWorkAreaJPanel.java
 *
 */
package UserInterface.HospitalManager;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.HospitalOrganization;
import Business.UserAccount.UserAccount;
import Business.InstantMessenging.Message;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AustinGnanaraj
 */
public class HospitalManagerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private HospitalOrganization organization;
    private UserAccount userAccount;
    private EcoSystem eco;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public HospitalManagerWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount ua, HospitalOrganization organization, EcoSystem eco) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = ua;
        this.eco = eco;
        hospitalNameJTextField.setText(enterprise.getOrganizationName());
        populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        hospitalNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnReply = new javax.swing.JButton();
        txtReply = new javax.swing.JTextField();
        btnManageNurse = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Hospital Manager WorkArea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        userJButton.setText("Manage User >>");
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 150, 30));

        manageOrganizationJButton.setText("Manage Doctor >>");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 150, 30));
        add(hospitalNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 160, 30));

        jLabel2.setText("Hospital Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Message", "Sender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 480, 100));

        btnReply.setText("Reply");
        btnReply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplyActionPerformed(evt);
            }
        });
        add(btnReply, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 220, -1));
        add(txtReply, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 460, 50));

        btnManageNurse.setText("Manage Nurse >>");
        btnManageNurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNurseActionPerformed(evt);
            }
        });
        add(btnManageNurse, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        ManageHospitalUserAccountJPanel mhjp = new ManageHospitalUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageHospitalUserAccountJPanel", mhjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed

        ManageDoctorsDetailsJPanel mddjp = new ManageDoctorsDetailsJPanel(userProcessContainer, enterprise, organization, userAccount);
        userProcessContainer.add("ManageDoctorsDetailsJPanel", mddjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void btnReplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplyActionPerformed
        //DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        //dtm.setRowCount(0);
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        } else if (txtReply.getText() == null) {
            JOptionPane.showMessageDialog(null, "Message cannot be empty");
            return;
        } else {
            Message m = (Message) jTable1.getValueAt(selectedRow, 0);
            Message mess2 = new Message();
            eco.getMessageDirectory().getWorkRequestList().add(mess2);
            mess2.setMessage(txtReply.getText());
            mess2.setSender(userAccount);
            mess2.setReceiver(m.getSender());
        }


    }//GEN-LAST:event_btnReplyActionPerformed

    private void btnManageNurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNurseActionPerformed

        ManageNurseDetailsJPanel mddjp = new ManageNurseDetailsJPanel(userProcessContainer, enterprise, organization, userAccount);
        userProcessContainer.add("ManageDoctorsDetailsJPanel", mddjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageNurseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageNurse;
    private javax.swing.JButton btnReply;
    private javax.swing.JTextField hospitalNameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JTextField txtReply;
    private javax.swing.JButton userJButton;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        for (WorkRequest work : eco.getMessageDirectory().getWorkRequestList()) {
            if (work.getReceiver() == null || work.getReceiver() == userAccount) {
                Message msg = (Message) work;
                Object[] row = new Object[2];
                row[0] = msg;
                row[1] = msg.getSender();
                dtm.addRow(row);
            }
        }
    }

}
