/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.Doctor.Adverse;

import Business.Doctor.Doctor;
import Business.Drug.Drug;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.AdverseEvents.AdverseDrugRequestDetail;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AustinGnanaraj
 */
public class ReviewAdverseEffectsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReviewAdverseEffectsJPanel
     */
    JPanel container;
    Drug d;
    UserAccount doc;
    Doctor doctor;
    EcoSystem eco;

    public ReviewAdverseEffectsJPanel(JPanel container,
            Drug d,
            UserAccount doc, Doctor doctor, EcoSystem eco) {
        initComponents();
        this.d = d;
        this.doctor = doctor;
        this.doc = doc;
        this.container = container;
        this.eco = eco;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reviewJTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reviewJTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewJTxtActionPerformed(evt);
            }
        });
        add(reviewJTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 190, 60));

        jButton1.setText("SUBMIT REVIEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 190, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void reviewJTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewJTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reviewJTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String message = reviewJTxt.getText();
        AdverseDrugRequestDetail adverseRequest = new AdverseDrugRequestDetail();
        adverseRequest.setDrug(d);
        adverseRequest.setMessage(message);
        adverseRequest.setSender(doc);
        adverseRequest.setStatus("warned");
        //doctor.getAdverseReportDirectory().getWorkRequestList().add(adverseRequest);
        eco.getAdverseReportDirectory().getWorkRequestList().add(adverseRequest);
        JOptionPane.showMessageDialog(null, "Submitted");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField reviewJTxt;
    // End of variables declaration//GEN-END:variables
}
