/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.Doctor;

import Business.Doctor.Doctor;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Person.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AustinGnanaraj
 */
public class AddDoctorsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private DoctorOrganization organization;

    /**
     * Creates new form AddDoctorsJPanel
     */
    public AddDoctorsJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = (HospitalEnterprise) enterprise;
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationDirectory()) {
            if (org instanceof DoctorOrganization) {
                this.organization = (DoctorOrganization) org;
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        doctorNameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ssnJTextField = new javax.swing.JTextField();
        contactNumberJTextField = new javax.swing.JTextField();
        addressJTextField = new javax.swing.JTextField();
        departmentNameJLabel = new javax.swing.JLabel();
        deptNameJTextField = new javax.swing.JTextField();
        addDoctorJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Create Doctor ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 13, -1, -1));

        jLabel2.setText("Doctor Name ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 64, -1, -1));
        add(doctorNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 61, 110, -1));

        jLabel3.setText("SSN");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 122, -1, -1));

        jLabel4.setText("Conact Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 195, -1, -1));

        jLabel6.setText("Address");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 266, -1, -1));
        add(ssnJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 131, 110, -1));
        add(contactNumberJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 192, 120, -1));
        add(addressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 252, 120, -1));

        departmentNameJLabel.setText("Department Name");
        add(departmentNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        deptNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptNameJTextFieldActionPerformed(evt);
            }
        });
        add(deptNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 130, -1));

        addDoctorJButton.setText("Add Doctor");
        addDoctorJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorJButtonActionPerformed(evt);
            }
        });
        add(addDoctorJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 360, 60));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 190, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void deptNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptNameJTextFieldActionPerformed

    private void addDoctorJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctorJButtonActionPerformed
        // TODO add your handling code here:

        String Name = doctorNameJTextField.getText();
        String Ssn = ssnJTextField.getText();
        long contactNumber = Long.parseLong(contactNumberJTextField.getText());

        //String  da = dateOfBirthJTextField.getText();
        String address = addressJTextField.getText();
        String department = deptNameJTextField.getText();

        Doctor d = ((HospitalEnterprise) enterprise).getDoctorDirectory().createDoctor();
        Person de = (Person) organization.getPersonDirectory().createPerson(Name);
        d.setName(Name);
        d.setSsn(Ssn);
        d.setPhoneNumber(contactNumber);
        d.setAddress(address);
        d.setDepartment(department);
        de.setSsn(Ssn);
        de.setPhoneNumber(contactNumber);
        de.setAddress(address);
        Doctor dee = (Doctor) de.getNewDoctor();
        dee.setDepartment(department);
        //  d.setDob(da);

        JOptionPane.showMessageDialog(null, "Doctor Added Successfully");


    }//GEN-LAST:event_addDoctorJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDoctorJButton;
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField contactNumberJTextField;
    private javax.swing.JLabel departmentNameJLabel;
    private javax.swing.JTextField deptNameJTextField;
    private javax.swing.JTextField doctorNameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField ssnJTextField;
    // End of variables declaration//GEN-END:variables
}
