/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.Doctor;

import Business.Doctor.Doctor;
import Business.EcoSystem;
import Business.Encounter.Encounter;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Patient.Patient;
import Business.VitalSign.VitalSign;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AustinGnanaraj
 */
public class AddPatientEncounterJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Patient patient;
    private Doctor doctor;
    private EcoSystem eco;
    private Network net;
    private HospitalEnterprise enterprise;
    private DoctorOrganization organization;

    public AddPatientEncounterJPanel(JPanel userContainer, Patient patient, Doctor doctor, EcoSystem eco, Network net, HospitalEnterprise enterprise, DoctorOrganization organization) {
        initComponents();
        this.userProcessContainer = userContainer;
        this.patient = patient;
        this.doctor = doctor;
        this.net = net;
        this.enterprise = enterprise;
        this.organization = organization;
        this.eco = eco;
        updateForm(patient);
        populateVitalSigns();
    }

    public void updateForm(Patient patient) {
        patientNameJTextField.setText(patient.getName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewDetailsJLabel = new javax.swing.JLabel();
        timeJLabel = new javax.swing.JLabel();
        timeJTextField = new javax.swing.JTextField();
        updateJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        chartJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        patientNameJTextField = new javax.swing.JTextField();
        descriptionJLabel = new javax.swing.JLabel();
        txtDiagnosis = new javax.swing.JTextField();
        orderDrugs = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVitalSigns = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSymptoms = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewDetailsJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        viewDetailsJLabel.setText("Create Encounter");
        add(viewDetailsJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        timeJLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        timeJLabel.setText("Time");
        add(timeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 150, 30));

        timeJTextField.setEnabled(false);
        add(timeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 230, 40));

        updateJButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        updateJButton.setText("Create Encounter >>");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });
        add(updateJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 230, 40));

        backJButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 320, 40));

        chartJButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        chartJButton.setText("View Chart");
        chartJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartJButtonActionPerformed(evt);
            }
        });
        add(chartJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 240, 50));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Patient Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 51, 130, 30));

        patientNameJTextField.setEnabled(false);
        add(patientNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 45, 230, 40));

        descriptionJLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        descriptionJLabel.setText("Diagnosis");
        add(descriptionJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 170, 40));

        txtDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagnosisActionPerformed(evt);
            }
        });
        add(txtDiagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 230, 40));

        orderDrugs.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        orderDrugs.setText("Prescribe Drugs >>");
        orderDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderDrugsActionPerformed(evt);
            }
        });
        add(orderDrugs, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 610, 50));

        tblVitalSigns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Test Date", "Respiratory Rate", "Heart Rate", "Systolic Blood Pressure", "Weight"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblVitalSigns);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 610, 140));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Symptoms");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 160, 50));
        add(txtSymptoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 230, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        // TODO add your handling code here:

        Encounter encounter = patient.getEncounterHistory().addEncounter();
        encounter.setDate();
        encounter.setDescriptionOfComplaint(txtDiagnosis.getText());
        encounter.setDoctorName(doctor.getName());
        encounter.setPatientName(patient.getName());
        encounter.setPatient(patient);
        encounter.setDoctor(doctor);


    }//GEN-LAST:event_updateJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void chartJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartJButtonActionPerformed
        // TODO add your handling code here:

        /*  float respiratoryRate = Float.parseFloat(respiratoryRateJTextField.getText());
         float heartRate = Float.parseFloat(heartRateJTextField.getText());
         float systolicBloodPressure = Float.parseFloat(systolicBPJTextField.getText());
         float weight = Float.parseFloat(weightJTextField.getText());

         DefaultCategoryDataset d = new DefaultCategoryDataset();
         d.setValue(new Double(heartRate), "Values", "heartrate");
         d.setValue(new Double(respiratoryRate), "Values", "respiratoryrate");
         d.setValue(new Double(systolicBloodPressure), "Values", "systolicBloodPressure");
         d.setValue(new Double(weight), "Values", "weight");

         JFreeChart chart = ChartFactory.createLineChart3D("VitalSign", "time", "values", d, PlotOrientation.VERTICAL, true, true, true);

         CategoryPlot T = chart.getCategoryPlot();
         ChartFrame f = new ChartFrame("line", chart);
         f.setVisible(true);
         f.setSize(450, 600);*/

    }//GEN-LAST:event_chartJButtonActionPerformed

    private void txtDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagnosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagnosisActionPerformed

    private void orderDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderDrugsActionPerformed
        OrderDrugsForPatientsJPanel pep = new OrderDrugsForPatientsJPanel(userProcessContainer, patient, doctor, eco, enterprise, organization, net);
        userProcessContainer.add("PatientEncounterJPanel", pep);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orderDrugsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton chartJButton;
    private javax.swing.JLabel descriptionJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton orderDrugs;
    private javax.swing.JTextField patientNameJTextField;
    private javax.swing.JTable tblVitalSigns;
    private javax.swing.JLabel timeJLabel;
    private javax.swing.JTextField timeJTextField;
    private javax.swing.JTextField txtDiagnosis;
    private javax.swing.JTextField txtSymptoms;
    private javax.swing.JButton updateJButton;
    private javax.swing.JLabel viewDetailsJLabel;
    // End of variables declaration//GEN-END:variables

    private void populateVitalSigns() {
        DefaultTableModel dtm = (DefaultTableModel) tblVitalSigns.getModel();
        dtm.setRowCount(0);
        Object[] row = new Object[5];
        for (VitalSign ve : patient.getVitalSignHistory().getVitalSignList()) {
            row[0] = ve;
            row[1] = ve.getRespiratoryRate();
            row[2] = ve.getHeartRate();
            row[3] = ve.getSystolicBloodPressure();
            row[4] = ve.getWeight();
            dtm.addRow(row);
        }
    }
}
