/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PatientAdminRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Patient.Patient;
import static Business.Roles.Role.RoleType.Patient;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AustinGnanaraj
 */
public class AddPatient extends javax.swing.JPanel {
    private Enterprise enterprise;
    private JPanel userProcessContainer;
    

    /**
     * Creates new form AddPatient
     */
    public AddPatient(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.enterprise = (HospitalEnterprise)enterprise;
        this.userProcessContainer = userProcessContainer;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientCreationJLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ssnJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        contactNumberJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        addPatientJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientCreationJLabel.setText("Patient Dashboard");
        add(patientCreationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 13, -1, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 65, -1, -1));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 82, -1));

        jLabel3.setText("SSN");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 103, -1, -1));
        add(ssnJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 114, 87, -1));

        jLabel4.setText("Conact Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 176, -1, -1));
        add(contactNumberJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 173, 94, -1));

        jLabel6.setText("Address");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 247, -1, -1));
        add(addressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 233, 124, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 362, -1, -1));

        addPatientJButton.setText("Add Patient");
        addPatientJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientJButtonActionPerformed(evt);
            }
        });
        add(addPatientJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 372, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addPatientJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientJButtonActionPerformed
        // TODO add your handling code here:

        String Name = nameJTextField.getText();
        String Ssn = ssnJTextField.getText();
        long contactNumber = Long.parseLong(contactNumberJTextField.getText());
        // String  da = dateOfBirthJTextField.getText();
        String address = addressJTextField.getText();
      //  String department = deptNameJTextField.getText();

        Patient pa =   ((HospitalEnterprise)enterprise).getPatientDirectory().createpatient();
        pa.setName(Name);
        pa.setSsn(Ssn);
        pa.setPhoneNumber(contactNumber);
        pa.setAddress(address);
        

        JOptionPane.showMessageDialog(null, "Patient Added Successfully");

    }//GEN-LAST:event_addPatientJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientJButton;
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField contactNumberJTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel patientCreationJLabel;
    private javax.swing.JTextField ssnJTextField;
    // End of variables declaration//GEN-END:variables
}
