/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientAdminRole;

import UserInterface.PatientAdminRole.EmergencyRequests.AttendEmergencyRequestsJPanel;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.PatientAdminOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author AustinGnanaraj
 */
public class PatientManagerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PatientAdminOrganization organization;
    private Enterprise enterprise;
    private UserAccount account;
    private EcoSystem eco;

    /**
     * Creates new form PatientManagementWorkAreaJPanel
     */
    public PatientManagerWorkAreaJPanel(JPanel userProcessContainer, PatientAdminOrganization organization, Enterprise enterprise, UserAccount account,EcoSystem eco) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.account = account;
        this.enterprise = enterprise;
        this.account = account;
        this.eco=eco;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managePatientsJButton = new javax.swing.JButton();
        encounterHistoryJButton = new javax.swing.JButton();
        userAccountForPatientsJButton = new javax.swing.JButton();
        patientAdminJLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        managePatientsJButton.setText("Manage Patients >>");
        managePatientsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePatientsJButtonActionPerformed(evt);
            }
        });
        add(managePatientsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 92, 243, 33));

        encounterHistoryJButton.setText("View Patient Encounter History >>");
        encounterHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encounterHistoryJButtonActionPerformed(evt);
            }
        });
        add(encounterHistoryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 167, 243, -1));

        userAccountForPatientsJButton.setText("Create User Account For Patients >>");
        userAccountForPatientsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAccountForPatientsJButtonActionPerformed(evt);
            }
        });
        add(userAccountForPatientsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 263, -1, -1));

        patientAdminJLabel.setText("Patient Admin WorkArea");
        add(patientAdminJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 13, -1, -1));

        jButton1.setText("Requests");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 332, 243, 41));
    }// </editor-fold>//GEN-END:initComponents

    private void managePatientsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePatientsJButtonActionPerformed
        // TODO add your handling code here:

        ManagePatientDetailsJPanel managePatientDetailsJPanel = new ManagePatientDetailsJPanel(userProcessContainer, enterprise, organization);
        userProcessContainer.add("managePatientDetailsJPanel", managePatientDetailsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_managePatientsJButtonActionPerformed

    private void encounterHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encounterHistoryJButtonActionPerformed
        // TODO add your handling code here:

        EncounterHistoryOfPatientsJPanel ehopjp = new EncounterHistoryOfPatientsJPanel(userProcessContainer, enterprise, organization);
        userProcessContainer.add("EncounterHistoryOfPatientsJPanel", ehopjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_encounterHistoryJButtonActionPerformed

    private void userAccountForPatientsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAccountForPatientsJButtonActionPerformed
        // TODO add your handling code here:

        ManagePatientsUserAccountJPanel mpuajp = new ManagePatientsUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManagePatientsUserAccountJPanel", mpuajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userAccountForPatientsJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AttendEmergencyRequestsJPanel attendRequests = new AttendEmergencyRequestsJPanel(userProcessContainer, enterprise, account, organization,eco);
        userProcessContainer.add("AttendRequestsJPanel", attendRequests);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton encounterHistoryJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton managePatientsJButton;
    private javax.swing.JLabel patientAdminJLabel;
    private javax.swing.JButton userAccountForPatientsJButton;
    // End of variables declaration//GEN-END:variables
}
