/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugManufacturerRole;

import Business.Drug.DrugDirectory;
import Business.EcoSystem;
import Business.Enterprise.DrugEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.DrugManufacturerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author AustinGnanaraj
 */
public class DrugManagerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private DrugManufacturerOrganization organization;
    private UserAccount account;
    private DrugDirectory dd;
    private EcoSystem ecoSystem;

    /**
     * Creates new form DrugManagerWorkAreaJPanel
     */
    public DrugManagerWorkAreaJPanel(JPanel userProcessContainer, DrugManufacturerOrganization organization, Enterprise enterprise, UserAccount account, EcoSystem ecoSystem) {
        initComponents();
        this.account = account;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAdverseEvents = new javax.swing.JButton();
        btnManageDrugs = new javax.swing.JButton();
        btnSupplyDrugs = new javax.swing.JButton();
        createDrugJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DrugManagerWorkArea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 13, -1, -1));

        btnAdverseEvents.setText("Adverse Events Handling");
        btnAdverseEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdverseEventsActionPerformed(evt);
            }
        });
        add(btnAdverseEvents, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 360, 50));

        btnManageDrugs.setText("Manage Drugs");
        btnManageDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDrugsActionPerformed(evt);
            }
        });
        add(btnManageDrugs, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 221, 340, 50));

        btnSupplyDrugs.setText("Supply Drugs");
        btnSupplyDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplyDrugsActionPerformed(evt);
            }
        });
        add(btnSupplyDrugs, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 310, 50));

        createDrugJButton.setText("Create Drug >> ");
        createDrugJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDrugJButtonActionPerformed(evt);
            }
        });
        add(createDrugJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdverseEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdverseEventsActionPerformed
        // TODO add your handling code here:

        ManageAdverseJPanel ad = new ManageAdverseJPanel(userProcessContainer, enterprise, ecoSystem, account);
        userProcessContainer.add("AddDrugsJPanel", ad);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_btnAdverseEventsActionPerformed

    private void btnManageDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDrugsActionPerformed
        // TODO add your handling code here:
        ManageDrugs ad = new ManageDrugs(userProcessContainer, organization, enterprise);
        userProcessContainer.add("AddDrugsJPanel", ad);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_btnManageDrugsActionPerformed

    private void btnSupplyDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplyDrugsActionPerformed
        SupplyDrugsJPanel ad = new SupplyDrugsJPanel(userProcessContainer, ecoSystem, (DrugEnterprise) enterprise);
        userProcessContainer.add("AddDrugsJPanel", ad);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSupplyDrugsActionPerformed

    private void createDrugJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDrugJButtonActionPerformed
        // TODO add your handling code here:

        AddDrugsJPanel ad = new AddDrugsJPanel(userProcessContainer, enterprise, dd);
        userProcessContainer.add("AddDrugsJPanel", ad);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_createDrugJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdverseEvents;
    private javax.swing.JButton btnManageDrugs;
    private javax.swing.JButton btnSupplyDrugs;
    private javax.swing.JButton createDrugJButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
