/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugManufacturerRole;

import Business.Drug.Drug;
import Business.Drug.DrugDirectory;
import Business.Enterprise.DrugEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.DrugManufacturerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AustinGnanaraj
 */
public class ManageDrugs extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private DrugManufacturerOrganization organization;
    private DrugDirectory dd;

    /**
     * Creates new form DrugManagerWorkAreaJPanel
     */
    public ManageDrugs(JPanel userProcessContainer, DrugManufacturerOrganization organization, Enterprise enterprise) {
        initComponents();
    
        this.enterprise = enterprise;
        this.organization = organization;
        this.userProcessContainer = userProcessContainer;
        populateDrugtable();
    }

    public void populateDrugtable() {
        DefaultTableModel dtm = (DefaultTableModel) drugJTable.getModel();
        dtm.setRowCount(0);

        for (Drug d : ((DrugEnterprise) enterprise).getDrugDirectory().getDrugDirectory()) {

            Object row[] = new Object[3];

            row[0] = d.getDrugName();
            row[1] = d.getManufacturingCompany();
            row[2] = d.getDrugComposition();

            /*row[4] = e.getVitalsign().getSystolicBloodPressure();
 
             row[5] = e.getVitalsign().getRespiratoryRate();
             row[6] = e.getVitalsign().getWeight();
             row[7] = e.getVitalsign().getHeartRate(); */
            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createDrugJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugJTable = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DrugManagerWorkArea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 13, -1, -1));

        createDrugJButton.setText("Create Drug >> ");
        createDrugJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDrugJButtonActionPerformed(evt);
            }
        });
        add(createDrugJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 160, -1));

        drugJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug Name", "Drug Manufacturer Name", "Drug Composition"
            }
        ));
        jScrollPane1.setViewportView(drugJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 47, 578, 144));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 221, -1, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 221, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createDrugJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDrugJButtonActionPerformed
        // TODO add your handling code here:

        AddDrugsJPanel ad = new AddDrugsJPanel(userProcessContainer, enterprise, dd);
        userProcessContainer.add("AddDrugsJPanel", ad);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_createDrugJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:

        populateDrugtable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createDrugJButton;
    private javax.swing.JTable drugJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    // End of variables declaration//GEN-END:variables
}
