/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugManufacturerRole;

import Business.Drug.Drug;
import Business.EcoSystem;
import Business.Enterprise.DrugEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.Network;
import Business.Stock.Stock;
import Business.WorkQueue.PharmacyRequestToManufacturerer;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AustinGnanaraj
 */
public class SupplyDrugsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplyDrugsJPanel
     */
    JPanel userProcessContainer;
    EcoSystem eco;
    DrugEnterprise e;

    public SupplyDrugsJPanel(JPanel userProcessContainer, EcoSystem eco, DrugEnterprise e) {
        initComponents();
        this.eco = eco;
        this.e = e;
        this.userProcessContainer = userProcessContainer;
        populateTable();
        populatecombo();
        populateDrug();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSupplhy = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        btnAddStocks = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug Name", "Pharmacy Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 59, 800, 110));

        btnSupplhy.setText("Supply Request Quantity");
        btnSupplhy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplhyActionPerformed(evt);
            }
        });
        add(btnSupplhy, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 310, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 190, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 240, 60));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 240, 60));
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 240, 80));

        btnAddStocks.setText("ADD STOCKS");
        btnAddStocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStocksActionPerformed(evt);
            }
        });
        add(btnAddStocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, 180, 90));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 240, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSupplhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplhyActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }

        PharmacyRequestToManufacturerer prm = (PharmacyRequestToManufacturerer) jTable1.getValueAt(selectedRow, 0);
        int q = Integer.parseInt(jTextField1.getText());
        prm.setQuantityOfDrugs(prm.getQuantityOfDrugs() + q);
        prm.setStatus("completed");
//            for (Network n : eco.getNetworkList()) {
//                for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
//                    if (e.getName().equals(prm.getPharmacyEnterprise().getName()) && e instanceof PharmacyEnterprise) {
//                        for (Stock s : ((PharmacyEnterprise) e).getStockDirectory().getStockDirectory()) {
//                            
//                            s.setQuantity(s.getQuantity() + q);
//                            break;
//                        }
//                    }
//                }
//            }
        int a = prm.getPharmacyEnterprise().getStockDirectory().getStockDirectory().size();
        if (a > 0) {
            for (Stock s : prm.getPharmacyEnterprise().getStockDirectory().getStockDirectory()) {
                if (s.getDrug().getDrugName().equals(prm.getDrug().getDrugName())) {
                    s.setQuantity(s.getQuantity() + q);
                    JOptionPane.showMessageDialog(null, "Request Complete");
                } else {
                    Stock ss = new Stock();
                    prm.getPharmacyEnterprise().getStockDirectory().getStockDirectory().add(ss);
                    ss.setDrug(prm.getDrug());
                    ss.setQuantity(q);
                    JOptionPane.showMessageDialog(null, "Request Complete");
                }
            }
        } else {
            Stock ss = new Stock();
            prm.getPharmacyEnterprise().getStockDirectory().getStockDirectory().add(ss);
            ss.setDrug(prm.getDrug());
            ss.setQuantity(q);
            JOptionPane.showMessageDialog(null, "Request Complete");
        }


    }//GEN-LAST:event_btnSupplhyActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Network n = (Network) jComboBox1.getSelectedItem();
        if (n != null) {
            populatePharmacy(n);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnAddStocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStocksActionPerformed
        Network n = (Network) jComboBox1.getSelectedItem();
        PharmacyEnterprise pe = (PharmacyEnterprise) jComboBox2.getSelectedItem();
        Drug d = (Drug) jComboBox3.getSelectedItem();
        for (Network ne : eco.getNetworkList()) {
            if (ne.getName().equals(n.getName())) {
                for (Enterprise pet : ne.getEnterpriseDirectory().getEnterpriseList()) {
                    if (pet.getName().equals(pe.getName())) {
                        for (Stock s : pe.getStockDirectory().getStockDirectory()) {
                            if (s.getDrug().getDrugName().equals(d.getDrugName())) {
                                Stock ss = new Stock();
                                ((PharmacyEnterprise) pet).getStockDirectory().getStockDirectory().add(ss);
                                ss.setDrug(d);
                                ss.setQuantity((int) jSpinner1.getValue());
                                JOptionPane.showMessageDialog(null, "Drug added");
                                break;
                            }
                        }

                    }
                }
            }
        }

    }//GEN-LAST:event_btnAddStocksActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStocks;
    private javax.swing.JButton btnSupplhy;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);

        for (WorkRequest e : eco.getDrugRequestToManufacturer().getWorkRequestList()) {
            PharmacyRequestToManufacturerer pe = (PharmacyRequestToManufacturerer) e;
            if (!pe.getStatus().equals("completed")) {
                Object row[] = new Object[3];
                row[0] = pe;
                row[1] = pe.getPharmacyEnterprise().getName();
                row[2] = pe.getQuantityOfDrugs();
                dtm.addRow(row);
            }

        }

    }

    private void populatecombo() {
        jComboBox1.removeAllItems();
        for (Network n : eco.getNetworkList()) {
            jComboBox1.addItem(n);
        }
    }

    private void populatePharmacy(Network n) {
        jComboBox2.removeAllItems();
        for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof PharmacyEnterprise) {
                jComboBox2.addItem(e);
            }
        }
    }

    private void populateDrug() {
        jComboBox3.removeAllItems();
        for (Drug d : e.getDrugDirectory().getDrugDirectory()) {
            jComboBox3.addItem(d);
        }
    }

}
